[package]
name = "kd-games"
description = "Kotodama: the Game trait, game mod profiles and their connectors (files, socket), finding Steam games"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kd-common.workspace = true
regex.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

