# The C runtime inside the program (Windows): players need no Visual C++ Redistributable installed. sherpa-onnx's
# prebuilt libraries use the static runtime too ("MT").
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
